### ISSUE TITLE
question for chain parameters

### ISSUE THREAD

**Issue by XClaws** [mfoll/BayeScan#2]
Dear Developer

Thank you for developing this nice toll for genome-wide SNPs searching tool.
After reading the manual and running the example, I still have a silly question about the chain parameters.  I am still confused about what the 'sample size' refers to.
Could you please elaborate it for me?

Thank you very much!

**Comment by mfoll** [comment]
Hi,

The sample size corresponds to the number of iterations the program will write out and use for estimation. The total number of iterations of the chain corresponds to the sample size multiplied by the thinning parameter.

Matthieu

**Comment by XClaws** [comment]
Thank you for your kind reply!
