### ISSUE TITLE
random seed is automatically set?

### ISSUE THREAD

**Issue by Carol-Symbiomics** [mfoll/BayeScan#3]
Dear Matthieu,

I would like to know if by default Bayescan uses a random seed for each MCMC run? 
If for instance, I would like to perform several runs of Bayescan how could I set the same seed for each run?

Thanks in advance!

**Comment by mfoll** [comment]
Dear Carol,

Indeed, Bayescan uses a random seed each time you run it and one for each chain. It is here in the code:
https://github.com/mfoll/BayeScan/blob/master/start.cpp#L153

I'm not sure why you would like to "set the same seed for each run", appart for reproducibility reasons? Unless there is a convergence issue, the seed used has a minimal impact on the final posterior.

Having a "seed" parameter could be easily added as a new feature if necessary, and I would be happy to accept a pull request for this.

**Comment by Carol-Symbiomics** [comment]
Thanks for your kind reply. Indeed, I was thinking of the seed parameter for reproducibility purposes.

If I may ask you another question, is it appropriate to evaluate the MCMC convergence by performing multiple runs with different Pr_odds? or is it necessary to perform several runs of the MCMC using exactly the same Pr_odds in each run? 

I've run myself BAYESCAN with different pr_odd and naturally the higher the value the fewer the SNPs identified as under selection. But the ones identified in pr_odd 500 are also detected at pr_odd 100

This might be a naive question, but I rather ask.

Thanks in advance,

**Comment by mfoll** [comment]
It would make sense to keep the prior odds fixed if you want to compare multiple runs and check the MCMC convergence. 
I never really experienced convergence issues, in particular I never saw different results across different runs like you could observe if the chain is trapped in a local maximum. I generally only look at the trace/running mean and autocorrelation to see if the chain has a good mixing.
