### ISSUE TITLE
Bayescan output without q-values

### ISSUE THREAD

**Issue by Charlesquantson** [mfoll/BayeScan#5]
Hello Matthieu,
I have run bayescan on my SNP data but the out came with q-values ( as show with the first five rows and the attached ). I would like to know what is the possible cause for this and also whether I could still identify loci under selection as the R function is based FDR which relies on Q-values.

    prob  log10(PO)  alpha  fst
1  0.0372671 -1.41218 0.0016344 0.0075413
2  0.099379 -0.95725 0.016275 0.0079540
3  0.062112 -1.1790 -0.0074971 0.0074606
4  0.080745 -1.0563 -0.044524 0.0072878
5  0.099379 -0.95725 -0.042782 0.0075401

Thanks in advance
Charles
  
[2RgamFinal_output_fst.txt](https://github.com/mfoll/BayeScan/files/5150153/2RgamFinal_output_fst.txt)

**Comment by ksolari** [comment]
I'm having the same issue. Even when I run it on the test_SNPs.txt file. Were you able to figure out what was going on? Thank you!
Katie

**Comment by ksolari** [comment]
For anyone else who runs across this issue - its because you're not using the latest version of Bayescan. Only version 2.1 (not 2.01) automatically generates q-values.
